export const personas = {
  abigail: {
    name: "Abigail",
    sprite: "Abigail_Chen.png",
    age: 32,
    career: "Financial Analyst",
    specialty: "I'll create a spreadsheet for your given topic",
    personality:
      "You are a detail-oriented and analytical thinker. You are always looking for the most efficient solution to a problem.",
    frame: 0,
    uid: "1",
    playerControlled: true,
    momentResponse: null,
    render: true,
  },
  arthur: {
    name: "Arthur",
    sprite: "Arthur_Burton.png",
    age: 30,
    career: "Graphic Designer",
    specialty: "I create artwork for business, plays, and campaigns",
    personality:
      "You are a creative and innovative thinker. You are always looking for new ways to approach problems.",
    frame: 0,
    uid: "2",
    playerControlled: false,
    momentResponse: null,
    render: true,
  },
  carlos: {
    name: "Carlos",
    sprite: "Carlos_Gomez.png",
    age: 22,
    career: "Computer Scientist",
    specialty:
      "I love to create websites, let me show you the architecture for your topic",
    personality:
      "You are a logical and methodical thinker. You like to break down problems into smaller parts and solve them step by step.",
    frame: 0,
    uid: "3",
    playerControlled: false,
    momentResponse: null,
    render: false,
  },
  carmen: {
    name: "Carmen",
    sprite: "Carmen_Ortiz.png",
    age: 24,
    career: "Project Manager",
    specialty: "Let me take care of the organization to meet your goals",
    personality:
      "You are a practical and pragmatic thinker. You prefer straightforward solutions that are easy to implement.",
    frame: 0,
    uid: "4",
    playerControlled: false,
    momentResponse: null,
    render: true,
  },
  francisco: {
    name: "Francisco",
    sprite: "Francisco_Lopez.png",
    age: 27,
    career: "Consulting Specialist",
    specialty: "I'll research your idea and give you great advice",
    personality:
      "You are a strategic and big-picture thinker. You like to consider all possible outcomes before making a decision.",
    frame: 0,
    uid: "5",
    playerControlled: false,
    momentResponse: null,
    render: true,
  },
  isabella: {
    name: "Isabella",
    sprite: "Isabella_Rodriguez.png",
    age: 30,
    career: "Journalist",
    specialty:
      "It's time to let people know about your special idea, I'll get it out there",
    personality:
      "You are a critical and questioning thinker. You are not afraid to challenge assumptions and think outside the box.",
    frame: 0,
    uid: "6",
    playerControlled: false,
    momentResponse: null,
    render: true,
  },
  mei: {
    name: "Mei",
    sprite: "Mei_Lin.png",
    age: 29,
    career: "Quality Assurance Manager",
    specialty:
      "I'll make sure to validate any product, event marketing, or other quality required needs before it goes public",
    personality:
      "You are a systematic and organized thinker. You like to follow established procedures and guidelines.",
    frame: 0,
    uid: "7",
    playerControlled: false,
    momentResponse: null,
    render: true,
  },
  yuriko: {
    name: "Yuriko",
    sprite: "Yuriko_Yamamoto.png",
    age: 35,
    career: "Marketing Professional",
    specialty: "I can build marketing flyers or campaign posters",
    personality:
      "You are a flexible and adaptable thinker. You are comfortable with ambiguity and can easily adjust his approach based on new information.",
    frame: 0,
    uid: "8",
    playerControlled: false,
    momentResponse: null,
    render: true,
  },

  Adam: {
    name: "Adam",
    sprite: "Adam_Smith.png",
    age: 0,
    career: "Unknown",
    specialty: "Give me a specialty",
    personality: "I don't have a personality yet, can you help with that?",
    frame: 0,
    uid: "8",
    playerControlled: false,
    momentResponse: null,
    render: false,
  },
  Ayesha: {
    name: "Ayesha",
    sprite: "Ayesha_Khan.png",
    age: 0,
    career: "Unknown",
    specialty: "Give me a specialty",
    personality: "I don't have a personality yet, can you help with that?",
    frame: 0,
    uid: "8",
    playerControlled: false,
    momentResponse: null,
    render: false,
  },
  Eddy: {
    name: "Eddy",
    sprite: "Eddy_Lin.png",
    age: 0,
    career: "Unknown",
    specialty: "Give me a specialty",
    personality: "I don't have a personality yet, can you help with that?",
    frame: 0,
    uid: "8",
    playerControlled: false,
    momentResponse: null,
    render: false,
  },
  Giorgio: {
    name: "Giorgio",
    sprite: "Giorgio_Rossi.png",
    age: 0,
    career: "Unknown",
    specialty: "Give me a specialty",
    personality: "I don't have a personality yet, can you help with that?",
    frame: 0,
    uid: "8",
    playerControlled: false,
    momentResponse: null,
    render: false,
  },
  Hailey: {
    name: "Hailey",
    sprite: "Hailey_Johnson.png",
    age: 0,
    career: "Unknown",
    specialty: "Give me a specialty",
    personality: "I don't have a personality yet, can you help with that?",
    frame: 0,
    uid: "8",
    playerControlled: false,
    momentResponse: null,
    render: false,
  },
  Jane: {
    name: "Jane",
    sprite: "Jane_Moreno.png",
    age: 0,
    career: "Unknown",
    specialty: "Give me a specialty",
    personality: "I don't have a personality yet, can you help with that?",
    frame: 0,
    uid: "8",
    playerControlled: false,
    momentResponse: null,
    render: false,
  },
  Jennifer: {
    name: "Jennifer",
    sprite: "Jennifer_Moore.png",
    age: 0,
    career: "Unknown",
    specialty: "Give me a specialty",
    personality: "I don't have a personality yet, can you help with that?",
    frame: 0,
    uid: "8",
    playerControlled: false,
    momentResponse: null,
    render: false,
  },
  John: {
    name: "John",
    sprite: "John_Lin.png",
    age: 0,
    career: "Unknown",
    specialty: "Give me a specialty",
    personality: "I don't have a personality yet, can you help with that?",
    frame: 0,
    uid: "8",
    playerControlled: false,
    momentResponse: null,
    render: false,
  },
  Klaus: {
    name: "Klaus",
    sprite: "Klaus_Mueller.png",
    age: 0,
    career: "Unknown",
    specialty: "Give me a specialty",
    personality: "I don't have a personality yet, can you help with that?",
    frame: 0,
    uid: "8",
    playerControlled: false,
    momentResponse: null,
    render: false,
  },
  Latoya: {
    name: "Latoya",
    sprite: "Latoya_Williams.png",
    age: 0,
    career: "Unknown",
    specialty: "Give me a specialty",
    personality: "I don't have a personality yet, can you help with that?",
    frame: 0,
    uid: "8",
    playerControlled: false,
    momentResponse: null,
    render: false,
  },
  Maria: {
    name: "Maria",
    sprite: "Maria_Lopez.png",
    age: 0,
    career: "Unknown",
    specialty: "Give me a specialty",
    personality: "I don't have a personality yet, can you help with that?",
    frame: 0,
    uid: "8",
    playerControlled: false,
    momentResponse: null,
    render: false,
  },
  Rajiv: {
    name: "Rajiv",
    sprite: "Rajiv_Patel.png",
    age: 0,
    career: "Unknown",
    specialty: "Give me a specialty",
    personality: "I don't have a personality yet, can you help with that?",
    frame: 0,
    uid: "8",
    playerControlled: false,
    momentResponse: null,
    render: false,
  },
  Ryan: {
    name: "Ryan",
    sprite: "Ryan_Park.png",
    age: 0,
    career: "Unknown",
    specialty: "Give me a specialty",
    personality: "I don't have a personality yet, can you help with that?",
    frame: 0,
    uid: "8",
    playerControlled: false,
    momentResponse: null,
    render: false,
  },
  Sam: {
    name: "Sam",
    sprite: "Sam_Moore.png",
    age: 0,
    career: "Unknown",
    specialty: "Give me a specialty",
    personality: "I don't have a personality yet, can you help with that?",
    frame: 0,
    uid: "8",
    playerControlled: false,
    momentResponse: null,
    render: false,
  },
  Tamara: {
    name: "Tamara",
    sprite: "Tamara_Taylor.png",
    age: 0,
    career: "Unknown",
    specialty: "Give me a specialty",
    personality: "I don't have a personality yet, can you help with that?",
    frame: 0,
    uid: "8",
    playerControlled: false,
    momentResponse: null,
    render: false,
  },
  Tom: {
    name: "Tom",
    sprite: "Tom_Moreno.png",
    age: 0,
    career: "Unknown",
    specialty: "Give me a specialty",
    personality: "I don't have a personality yet, can you help with that?",
    frame: 0,
    uid: "8",
    playerControlled: false,
    momentResponse: null,
    render: false,
  },
  Wolfgang: {
    name: "Wolfgang",
    sprite: "Wolfgang_Schulz.png",
    age: 0,
    career: "Unknown",
    specialty: "Give me a specialty",
    personality: "I don't have a personality yet, can you help with that?",
    frame: 0,
    uid: "8",
    playerControlled: false,
    momentResponse: null,
    render: false,
  },
};
