export const personas = {
  abigail: {
    name: "Abigail",
    sprite: "Abigail_Chen.png",
    personality:
      "Abigail is a detail-oriented and analytical thinker. She is always looking for the most efficient solution to a problem.",
    x: 30,
    y: 26,
    direction: "down",
    frame: 0,
    uid: "1",
    playerControlled: true,
  },
  arthur: {
    name: "Arthur",
    sprite: "Arthur_Burton.png",
    personality:
      "Arthur is a creative and innovative thinker. He is always looking for new ways to approach problems.",
    x: 10,
    y: 19,
    direction: "right",
    frame: 0,
    uid: "2",
    playerControlled: false,
  },
  carlos: {
    name: "Carlos",
    sprite: "Carlos_Gomez.png",
    personality:
      "Carlos is a logical and methodical thinker. He likes to break down problems into smaller parts and solve them step by step.",
    x: 30,
    y: 6,
    direction: "down",
    frame: 0,
    uid: "3",
    playerControlled: false,
  },
  carmen: {
    name: "Carmen",
    sprite: "Carmen_Ortiz.png",
    personality:
      "Carmen is a practical and pragmatic thinker. She prefers straightforward solutions that are easy to implement.",
    x: 14,
    y: 16,
    direction: "down",
    frame: 0,
    uid: "4",
    playerControlled: false,
  },
  francisco: {
    name: "Francisco",
    sprite: "Francisco_Lopez.png",
    personality:
      "Francisco is a strategic and big-picture thinker. He likes to consider all possible outcomes before making a decision.",
    x: 81,
    y: 19,
    direction: "right",
    frame: 0,
    uid: "5",
    playerControlled: false,
  },
  isabella: {
    name: "Isabella",
    sprite: "Isabella_Rodriguez.png",
    personality:
      "Isabella is a critical and questioning thinker. She is not afraid to challenge assumptions and think outside the box.",
    x: 52,
    y: 32,
    direction: "left",
    frame: 0,
    uid: "6",
    playerControlled: false,
  },
  mei: {
    name: "Mei",
    sprite: "Mei_Lin.png",
    personality:
      "Mei is a systematic and organized thinker. She likes to follow established procedures and guidelines.",
    x: 57,
    y: 17,
    direction: "left",
    frame: 0,
    uid: "7",
    playerControlled: false,
  },
  yuriko: {
    name: "Yuriko",
    sprite: "Yuriko_Yamamoto.png",
    personality:
      "Yuriko is a flexible and adaptable thinker. He is comfortable with ambiguity and can easily adjust his approach based on new information.",
    x: 26,
    y: 34,
    direction: "down",
    frame: 0,
    uid: "8",
    playerControlled: false,
  },
};
