export const agentRenderPositions = [
  { x: 8, y: 16, direction: "right" },
  { x: 15, y: 18, direction: "left" },
  { x: 11, y: 28, direction: "down" },
  { x: 19, y: 30, direction: "up" },
  { x: 22, y: 15, direction: "up" },
  { x: 23, y: 22, direction: "down" },
  { x: 25, y: 4, direction: "down" },
  { x: 43, y: 13, direction: "down" },
  { x: 33, y: 21, direction: "right" },
  { x: 30, y: 28, direction: "up" },
  { x: 37, y: 27, direction: "left" },
  { x: 42, y: 30, direction: "down" },
  { x: 64, y: 14, direction: "down" },
  { x: 74, y: 14, direction: "up" },
  { x: 68, y: 2, direction: "right" },
  { x: 52, y: 37, direction: "down" },
  { x: 38, y: 16, direction: "down" },
  { x: 7, y: 30, direction: "right" },
  { x: 24, y: 38, direction: "right" },
  { x: 52, y: 12, direction: "down" },
  { x: 31, y: 24, direction: "up" },
  { x: 52, y: 39, direction: "right" },
  { x: 58, y: 39, direction: "left" },
];
