const agentRenderPositions = [
  { x: 8, y: 14, direction: "right" },
  { x: 40, y: 31, direction: "left" },
  { x: 18, y: 30, direction: "right" },
  { x: 39, y: 37, direction: "right" },
  { x: 63, y: 37, direction: "down" },
  { x: 69, y: 16, direction: "down" },
  { x: 68, y: 22, direction: "left" },
  { x: 56, y: 3, direction: "down" },
  { x: 25, y: 7, direction: "down" },
  { x: 19, y: 22, direction: "up" },
  { x: 13, y: 14, direction: "right" },
  { x: 17, y: 14, direction: "left" },
  { x: 42, y: 12, direction: "down" },
  { x: 44, y: 15, direction: "up" },
  { x: 38, y: 31, direction: "left" },
  { x: 30, y: 20, direction: "left" },
  { x: 61, y: 4, direction: "down" },
  { x: 65, y: 4, direction: "left" },
  { x: 50, y: 35, direction: "right" },
  { x: 52, y: 35, direction: "left" },
  { x: 24, y: 26, direction: "down" },
  { x: 27, y: 7, direction: "left" },
  { x: 27, y: 14, direction: "down" },
  { x: 11, y: 19, direction: "up" },
  { x: 11, y: 17, direction: "down" },
];
