/**
 * Locations for moment conversation meetings
 */
export const meetingPlaces = {
  // groceryStore: {
  //   title: "Grocery Store",
  //   primaryAgent: { x: 43, y: 25, direction: "down" },
  //   audiencePositions: [
  //     { x: 46, y: 27, direction: "left" },
  //     { x: 45, y: 29, direction: "left" },
  //     { x: 47, y: 32, direction: "up" },
  //     { x: 38, y: 29, direction: "up" },
  //     { x: 37, y: 33, direction: "up" },
  //     { x: 42, y: 32, direction: "up" },
  //     { x: 33, y: 28, direction: "right" },
  //   ],
  //   screenStyles: {
  //     position: "absolute",
  //     left: "59em",
  //     top: "0em",
  //     width: "10em",
  //     height: "8em",
  //   },
  //   overlayStyles: {
  //     position: "absolute",
  //     left: "60em",
  //     top: "1em",
  //     width: "8em",
  //     height: "4em",
  //   },
  // },
  // plazaTable: {
  //   title: "The Plaza",
  //   primaryAgent: { x: 26, y: 16, direction: "down" },
  //   audiencePositions: [
  //     { x: 31, y: 29, direction: "up" },
  //     { x: 30, y: 22, direction: "left" },
  //     { x: 25, y: 26, direction: "up" },
  //     { x: 30, y: 30, direction: "up" },
  //     { x: 30, y: 19, direction: "left" },
  //     { x: 17, y: 24, direction: "up" },
  //     { x: 14, y: 19, direction: "right" },
  //     { x: 20, y: 23, direction: "up" },
  //     { x: 25, y: 21, direction: "up" },
  //     { x: 34, y: 25, direction: "left" },
  //   ],
  //   screenStyles: {
  //     position: "absolute",
  //     left: "32em",
  //     top: "-20em",
  //     width: "10em",
  //     height: "8em",
  //   },
  //   overlayStyles: {
  //     position: "absolute",
  //     left: "33em",
  //     top: "-19em",
  //     width: "8em",
  //     height: "4em",
  //   },
  // },
  theFlat: {
    title: "The Flat",
    primaryAgent: { x: 66, y: 6, direction: "down" },
    audiencePositions: [
      { x: 68, y: 17, direction: "up" },
      { x: 62, y: 18, direction: "up" },
      { x: 67, y: 18, direction: "up" },
      { x: 62, y: 12, direction: "right" },
    ],
    screenStyles: {
      position: "absolute",
      left: "111rem",
      top: "-23em",
      width: "10em",
      height: "8em",
      transform: "perspective(0em) rotateY(0deg) rotateZ(0deg)",
      transformOrigin: "left",
    },
    overlayStyles: {
      position: "absolute",
      left: "112em",
      top: "-22em",
      width: "8em",
      height: "4em",
      transform: "perspective(200px) rotateY(0deg) rotateZ(0deg)",
      transformOrigin: "left",
    },
  },
  // theDeck: {
  //   primaryAgent: { x: 80, y: 25, direction: "right" },
  //   audiencePositions: [
  //     { x: 92, y: 21, direction: "down" },
  //     { x: 87, y: 24, direction: "left" },
  //     { x: 85, y: 20, direction: "down" },
  //     { x: 86, y: 26, direction: "left" },
  //     { x: 89, y: 26, direction: "left" },
  //     { x: 93, y: 26, direction: "left" },
  //   ],
  //   screenStyles: {
  //     position: "absolute",
  //     left: "1590px",
  //     top: "370px",
  //     transform: "perspective(200px) rotateY(20deg) rotateZ(-7deg)",
  //     transformOrigin: "left",
  //   },
  //   overlayStyles: {
  //     position: "absolute",
  //     left: "1610px",
  //     top: "392px",
  //     width: "75px",
  //     height: "57px",
  //     transform: "perspective(200px) rotateY(20deg) rotateZ(-6deg)",
  //     transformOrigin: "left",
  //   },
  // },
  // bizarreStreet: {
  //   primaryAgent: { x: 55, y: 45, direction: "down" },
  //   audiencePositions: [
  //     { x: 49, y: 45, direction: "right" },
  //     { x: 46, y: 46, direction: "right" },
  //     { x: 62, y: 45, direction: "left" },
  //     { x: 62, y: 47, direction: "left" },
  //     { x: 53, y: 48, direction: "up" },
  //     { x: 51, y: 48, direction: "up" },
  //     { x: 55, y: 48, direction: "up" },
  //   ],
  //   screenStyles: {
  //     position: "absolute",
  //     left: "1150px",
  //     top: "830px",
  //     transform: "perspective(800px) rotateY(-20deg) rotateZ(10deg)",
  //     transformOrigin: "left",
  //   },
  //   overlayStyles: {
  //     position: "absolute",
  //     left: "1177px",
  //     top: "859px",
  //     width: "75px",
  //     height: "57px",
  //     transform: "perspective(700px) rotateY(-20deg) rotateZ(10deg)",
  //     transformOrigin: "left",
  //   },
  // },
};
