/**
 * Locations for moment conversation meetings
 */
export const meetingPlaces = {
  groceryStore: {
    primaryAgent: { x: 52, y: 30, direction: "down" },
    audiencePositions: [
      { x: 52, y: 36, direction: "up" },
      { x: 48, y: 36, direction: "up" },
      { x: 50, y: 35, direction: "up" },
      { x: 54, y: 33, direction: "up" },
      { x: 59, y: 32, direction: "left" },
      { x: 58, y: 34, direction: "left" },
      { x: 56, y: 35, direction: "up" },
    ],
    screenStyles: {
      position: "absolute",
      left: "920px",
      top: "590px",
      transform: "perspective(200px) rotateY(20deg) rotateZ(-7deg)",
      transformOrigin: "left",
    },
    overlayStyles: {
      position: "absolute",
      left: "940px",
      top: "612px",
      width: "75px",
      height: "57px",
      transform: "perspective(200px) rotateY(20deg) rotateZ(-6deg)",
      transformOrigin: "left",
    },
  },
  plazaTable: {
    primaryAgent: { x: 29, y: 18, direction: "down" },
    audiencePositions: [
      { x: 19, y: 21, direction: "right" },
      { x: 23, y: 26, direction: "up" },
      { x: 27, y: 29, direction: "up" },
      { x: 30, y: 30, direction: "up" },
      { x: 33, y: 30, direction: "up" },
      { x: 39, y: 20, direction: "left" },
      { x: 39, y: 26, direction: "left" },
      { x: 27, y: 25, direction: "up" },
      { x: 33, y: 26, direction: "up" },
      { x: 32, y: 35, direction: "up" },
    ],
    screenStyles: {
      position: "absolute",
      left: "420px",
      top: "330px",
      transform: "perspective(200px) rotateY(20deg) rotateZ(-7deg)",
      transformOrigin: "left",
    },
    overlayStyles: {
      position: "absolute",
      left: "440px",
      top: "352px",
      width: "75px",
      height: "57px",
      transform: "perspective(200px) rotateY(20deg) rotateZ(-6deg)",
      transformOrigin: "left",
    },
  },
  theFlat: {
    primaryAgent: { x: 86, y: 7, direction: "down" },
    audiencePositions: [
      { x: 88, y: 17, direction: "up" },
      { x: 82, y: 20, direction: "up" },
      { x: 87, y: 19, direction: "up" },
      { x: 81, y: 12, direction: "right" },
    ],
    screenStyles: {
      position: "absolute",
      left: "1600px",
      top: "120px",
      transform: "perspective(200px) rotateY(20deg) rotateZ(-7deg)",
      transformOrigin: "left",
    },
    overlayStyles: {
      position: "absolute",
      left: "1620px",
      top: "142px",
      width: "75px",
      height: "57px",
      transform: "perspective(200px) rotateY(20deg) rotateZ(-6deg)",
      transformOrigin: "left",
    },
  },
  theDeck: {
    primaryAgent: { x: 80, y: 25, direction: "right" },
    audiencePositions: [
      { x: 92, y: 21, direction: "down" },
      { x: 87, y: 24, direction: "left" },
      { x: 85, y: 20, direction: "down" },
      { x: 86, y: 26, direction: "left" },
      { x: 89, y: 26, direction: "left" },
      { x: 93, y: 26, direction: "left" },
    ],
    screenStyles: {
      position: "absolute",
      left: "1590px",
      top: "370px",
      transform: "perspective(200px) rotateY(20deg) rotateZ(-7deg)",
      transformOrigin: "left",
    },
    overlayStyles: {
      position: "absolute",
      left: "1610px",
      top: "392px",
      width: "75px",
      height: "57px",
      transform: "perspective(200px) rotateY(20deg) rotateZ(-6deg)",
      transformOrigin: "left",
    },
  },
  bizarreStreet: {
    primaryAgent: { x: 55, y: 45, direction: "down" },
    audiencePositions: [
      { x: 49, y: 45, direction: "right" },
      { x: 46, y: 46, direction: "right" },
      { x: 62, y: 45, direction: "left" },
      { x: 62, y: 47, direction: "left" },
      { x: 53, y: 48, direction: "up" },
      { x: 51, y: 48, direction: "up" },
      { x: 55, y: 48, direction: "up" },
    ],
    screenStyles: {
      position: "absolute",
      left: "1150px",
      top: "830px",
      transform: "perspective(800px) rotateY(-20deg) rotateZ(10deg)",
      transformOrigin: "left",
    },
    overlayStyles: {
      position: "absolute",
      left: "1177px",
      top: "859px",
      width: "75px",
      height: "57px",
      transform: "perspective(700px) rotateY(-20deg) rotateZ(10deg)",
      transformOrigin: "left",
    },
  },
};
